Feature/custom state fields
vlingo/vlingo-xoom-starter pull request #23
Opened 2021-02-24 23:28 UTC by abdullahcalisir12

adding custom state field feature is added/

2021-02-25 03:49 UTC, hurelhuyag requested changes
I think those git merge errors needs to be fixed.

2021-02-25 03:49 UTC, hurelhuyag commented on src/main/frontend/src/routes/_layout.svelte
> +<<<<<<< HEAD
I same several this kind of lines. I think this shouldn't be here.

2021-02-25 03:58 UTC, VaughnVernon commented
@abdullahcalisir12 We can't build to test. There are merge conflicts in the Svelte code. Neither @hurelhuyag nor I are able to review Svelte code but we were trying to do usability testing.

2021-02-25 06:17 UTC, VaughnVernon reviewed
@abdullahcalisir12 Would you also please support the basic type `Date`?

It is a placeholder type that will be translated for each platform, such as Java `LocalDate` and .NET `DateTime`.

2021-02-25 20:00 UTC, abdullahcalisir12 commented
Sorry @VaughnVernon @hurelhuyag for the merge conflicts, I wasn't aware of them. I just updated PR, can you review it?

2021-03-02 04:15 UTC, hurelhuyag approved these changes

2021-03-02 04:24 UTC, hurelhuyag commented
I tried to run. Comboboxes, Modal dialogs not working.

2021-03-02 04:39 UTC, hurelhuyag commented
I also noticed this weird animation. Is this related to PR? or different issue?
![Screencast 2021-03-02 12:35:21](https://user-images.githubusercontent.com/1059242/109598441-46c95100-7b54-11eb-893c-1deb08b15c6f.gif)

2021-03-03 04:40 UTC, hurelhuyag approved these changes

2021-03-03 04:52 UTC, merged